

[source]
type = "join"
how = "left"
left_on = "Foo"
right_on = "Foo"

[source.left]
type = "csv"
path = "test.csv"

[source.right]
type = "csv"
path = "test2.csv"


[export]
folder = "./output"
name = "export"
