#:schema schema.json

source.csv.path = "test.csv"

[[transforms]]
[transforms.join]
right.csv.path = "test2.csv"
how = "left"
left_on = "Foo"
right_on = "Foo"

[[transforms]]
select = [
    { expr = { col = "*"}},
    { expr = { lit = "5"}, ops = [
        { alias = "foobar"}
    ] }
]



[[exports]]
type = "csv"
folder = "./output/test"
date_format = "_%FT%T"
name = "export"
