#:schema schema.json

source.csv.path = "test.csv"

[[transforms]]
[transforms.join]
right.csv.path = "test2.csv"
how = "left"
left_on = "Foo"
right_on = "Foo"

[[exports]]
type = "csv"
folder = "./output/test"
date_format = "_%FT%T"
name = "export"
